
// USER
export const TOGGLE_LOGGED_IN = "TOGGLE_LOGGED_IN";
export const SET_USER_INFO = "SET_USER_INFO";
export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const SET_USER_ERROR = "SET_USER_ERROR";

// SEARCH
export const SET_SOURCE = 'SET_SOURCE';
export const SET_DESTINATION = 'SET_DESTINATION';
export const SET_JOURNEY_DATE = 'SET_JOURNEY_DATE';
export const SET_RESULTS = 'SET_RESULTS';

// BUSES
export const FETCH_BUSES_START = 'FETCH_BUSES_START';
export const SET_BUSES = 'SET_BUSES';
export const FETCH_BUSES_END = 'FETCH_BUSES_END';

// BOOKING
export const SET_BOOKING_SEATS = 'SET_BOOKING SEATS';
export const SET_PASSENGERS_DETAIL = 'SET_PASSENGERS_DETAIL';
